# Generated by Django 3.1.3 on 2020-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Customer'), (1, 'Seller')], default=0)),
                ('targetEndpoint', models.CharField(max_length=120)),
                ('microServiceName', models.CharField(max_length=120)),
                ('access', models.IntegerField(choices=[(0, 'Notallowed'), (16, 'Delete'), (8, 'Update'), (4, 'Create'), (2, 'List'), (1, 'Retrieve'), (24, 'Delete Update'), (20, 'Delete Create'), (18, 'Delete List'), (17, 'Delete Retrieve'), (12, 'Update Create'), (10, 'Update List'), (9, 'Update Retrieve'), (6, 'Create List'), (5, 'Create Retrieve'), (3, 'List Retrieve'), (28, 'Delete Update Create'), (26, 'Delete Update List'), (25, 'Delete Update Retrieve'), (22, 'Delete Create List'), (21, 'Delete Create Retrieve'), (19, 'Delete List Retrieve'), (14, 'Update Create List'), (13, 'Update Create Retrieve'), (11, 'Update List Retrieve'), (7, 'Create List Retrieve'), (30, 'Delete Update Create List'), (29, 'Delete Update Create Retrieve'), (27, 'Delete Update List Retrieve'), (23, 'Delete Create List Retrieve'), (15, 'Update Create List Retrieve'), (31, 'Delete Update Create List Retrieve')], default=0)),
            ],
        ),
    ]
