apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-postgres
spec:
  serviceName: "db-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: db-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "Auth-core"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: authcore-db
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authcore-db
                  key: postgres-password
          ports:
            - containerPort: 5432
              name: postgredb
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgress-claim
