apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
  labels:
    app: auth-postgres
spec:
  ports:
    - port: 5432
      name: db-postgres
  clusterIP: None
  selector:
    app: db-postgres