apiVersion: v1
kind: Service
metadata:
  labels:
    app: django-auth
    type: backend
  name: django-auth
  namespace: abrishami-cloud
spec:
  type: NodePort
  ports:
    - name: "django-auth-service"
      port: 8000
      targetPort: 8000
      nodePort: 31050
  selector:
    app: django-auth
    type: backend