# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservices_Auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='microservices_Auth.proto',
  package='AuthCoreProto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18microservices_Auth.proto\x12\rAuthCoreProto\x1a\x1bgoogle/protobuf/empty.proto\"P\n\rAccessRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x16\n\x0etargetEndpoint\x18\x02 \x01(\t\x12\x18\n\x10microServiceName\x18\x03 \x01(\t\"p\n\rAccessRespose\x12\x10\n\x08retrieve\x18\x01 \x01(\x08\x12\x0c\n\x04list\x18\x02 \x01(\x08\x12\x0e\n\x06\x63reate\x18\x03 \x01(\x08\x12\x0e\n\x06update\x18\x04 \x01(\x08\x12\x0e\n\x06\x64\x65lete\x18\x05 \x01(\x08\x12\x0f\n\x07user_id\x18\x64 \x01(\x05\x32Y\n\rAccessControl\x12H\n\x08Retrieve\x12\x1c.AuthCoreProto.AccessRequest\x1a\x1c.AuthCoreProto.AccessRespose\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ACCESSREQUEST = _descriptor.Descriptor(
  name='AccessRequest',
  full_name='AuthCoreProto.AccessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='AuthCoreProto.AccessRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetEndpoint', full_name='AuthCoreProto.AccessRequest.targetEndpoint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='microServiceName', full_name='AuthCoreProto.AccessRequest.microServiceName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=152,
)


_ACCESSRESPOSE = _descriptor.Descriptor(
  name='AccessRespose',
  full_name='AuthCoreProto.AccessRespose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retrieve', full_name='AuthCoreProto.AccessRespose.retrieve', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list', full_name='AuthCoreProto.AccessRespose.list', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create', full_name='AuthCoreProto.AccessRespose.create', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update', full_name='AuthCoreProto.AccessRespose.update', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delete', full_name='AuthCoreProto.AccessRespose.delete', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='AuthCoreProto.AccessRespose.user_id', index=5,
      number=100, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['AccessRequest'] = _ACCESSREQUEST
DESCRIPTOR.message_types_by_name['AccessRespose'] = _ACCESSRESPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccessRequest = _reflection.GeneratedProtocolMessageType('AccessRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSREQUEST,
  '__module__' : 'microservices_Auth_pb2'
  # @@protoc_insertion_point(class_scope:AuthCoreProto.AccessRequest)
  })
_sym_db.RegisterMessage(AccessRequest)

AccessRespose = _reflection.GeneratedProtocolMessageType('AccessRespose', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSRESPOSE,
  '__module__' : 'microservices_Auth_pb2'
  # @@protoc_insertion_point(class_scope:AuthCoreProto.AccessRespose)
  })
_sym_db.RegisterMessage(AccessRespose)



_ACCESSCONTROL = _descriptor.ServiceDescriptor(
  name='AccessControl',
  full_name='AuthCoreProto.AccessControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=268,
  serialized_end=357,
  methods=[
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='AuthCoreProto.AccessControl.Retrieve',
    index=0,
    containing_service=None,
    input_type=_ACCESSREQUEST,
    output_type=_ACCESSRESPOSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCESSCONTROL)

DESCRIPTOR.services_by_name['AccessControl'] = _ACCESSCONTROL

# @@protoc_insertion_point(module_scope)
